after_script:
  - "if [[ `node --version` =~ ^v10 ]] ; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT ; fi"

before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"

env:
  global:
    - CODECLIMATE_REPO_TOKEN=850b9d6e5ffc53ec18a7d513c19401ce553856315e35e737e5be75e5b6f04f4f

sudo: false

language: node_js

node_js:
  - "14"
  - "12"
  - "10"

script: "npm run coverage"
