"use strict";

const types = {
  address: { short: "a", size: 20 },
  auto:    {},
  byte:    { short: "b1", size: 1, bytes: true },
  bytes1:  { short: "b1", size: 1, bytes: true },
  bytes2:  { short: "b2", size: 2, bytes: true },
  bytes3:  { short: "b3", size: 3, bytes: true },
  bytes4:  { short: "b4", size: 4, bytes: true },
  bytes5:  { short: "b5", size: 5, bytes: true },
  bytes6:  { short: "b6", size: 6, bytes: true },
  bytes7:  { short: "b7", size: 7, bytes: true },
  bytes8:  { short: "b8", size: 8, bytes: true },
  bytes9:  { short: "b9", size: 9, bytes: true },
  bytes10: { short: "b10", size: 10, bytes: true },
  bytes11: { short: "b11", size: 11, bytes: true },
  bytes12: { short: "b12", size: 12, bytes: true },
  bytes13: { short: "b13", size: 13, bytes: true },
  bytes14: { short: "b14", size: 14, bytes: true },
  bytes15: { short: "b15", size: 15, bytes: true },
  bytes16: { short: "b16", size: 16, bytes: true },
  bytes17: { short: "b17", size: 17, bytes: true },
  bytes18: { short: "b18", size: 18, bytes: true },
  bytes19: { short: "b19", size: 19, bytes: true },
  bytes20: { short: "b20", size: 20, bytes: true },
  bytes21: { short: "b21", size: 21, bytes: true },
  bytes22: { short: "b22", size: 22, bytes: true },
  bytes23: { short: "b23", size: 23, bytes: true },
  bytes24: { short: "b24", size: 24, bytes: true },
  bytes25: { short: "b25", size: 25, bytes: true },
  bytes26: { short: "b26", size: 26, bytes: true },
  bytes27: { short: "b27", size: 27, bytes: true },
  bytes28: { short: "b28", size: 28, bytes: true },
  bytes29: { short: "b29", size: 29, bytes: true },
  bytes30: { short: "b30", size: 30, bytes: true },
  bytes31: { short: "b31", size: 31, bytes: true },
  bytes32: { short: "b32", size: 32, bytes: true },
  int8:    { short: "i1", size: 1, integer: true, signed: true },
  int16:   { short: "i2", size: 2, integer: true, signed: true },
  int24:   { short: "i3", size: 3, integer: true, signed: true },
  int32:   { short: "i4", size: 4, integer: true, signed: true },
  int40:   { short: "i5", size: 5, integer: true, signed: true },
  int48:   { short: "i6", size: 6, integer: true, signed: true },
  int56:   { short: "i7", size: 7, integer: true, signed: true },
  int64:   { short: "i8", size: 8, integer: true, signed: true },
  int72:   { short: "i9", size: 9, integer: true, signed: true },
  int80:   { short: "i10", size: 10, integer: true, signed: true },
  int88:   { short: "i11", size: 11, integer: true, signed: true },
  int96:   { short: "i12", size: 12, integer: true, signed: true },
  int104:  { short: "i13", size: 13, integer: true, signed: true },
  int112:  { short: "i14", size: 14, integer: true, signed: true },
  int120:  { short: "i15", size: 15, integer: true, signed: true },
  int128:  { short: "i16", size: 16, integer: true, signed: true },
  int136:  { short: "i17", size: 17, integer: true, signed: true },
  int144:  { short: "i18", size: 18, integer: true, signed: true },
  int152:  { short: "i19", size: 19, integer: true, signed: true },
  int160:  { short: "i20", size: 20, integer: true, signed: true },
  int168:  { short: "i21", size: 21, integer: true, signed: true },
  int176:  { short: "i22", size: 22, integer: true, signed: true },
  int184:  { short: "i23", size: 23, integer: true, signed: true },
  int192:  { short: "i24", size: 24, integer: true, signed: true },
  int200:  { short: "i25", size: 25, integer: true, signed: true },
  int208:  { short: "i26", size: 26, integer: true, signed: true },
  int216:  { short: "i27", size: 27, integer: true, signed: true },
  int224:  { short: "i28", size: 28, integer: true, signed: true },
  int232:  { short: "i29", size: 29, integer: true, signed: true },
  int240:  { short: "i30", size: 30, integer: true, signed: true },
  int248:  { short: "i31", size: 31, integer: true, signed: true },
  int256:  { short: "i32", size: 32, integer: true, signed: true },
  uint8:   { short: "u1", size: 1, integer: true },
  uint16:  { short: "u2", size: 2, integer: true },
  uint24:  { short: "u3", size: 3, integer: true },
  uint32:  { short: "u4", size: 4, integer: true },
  uint40:  { short: "u5", size: 5, integer: true },
  uint48:  { short: "u6", size: 6, integer: true },
  uint56:  { short: "u7", size: 7, integer: true },
  uint64:  { short: "u8", size: 8, integer: true },
  uint72:  { short: "u9", size: 9, integer: true },
  uint80:  { short: "u10", size: 10, integer: true },
  uint88:  { short: "u11", size: 11, integer: true },
  uint96:  { short: "u12", size: 12, integer: true },
  uint104: { short: "u13", size: 13, integer: true },
  uint112: { short: "u14", size: 14, integer: true },
  uint120: { short: "u15", size: 15, integer: true },
  uint128: { short: "u16", size: 16, integer: true },
  uint136: { short: "u17", size: 17, integer: true },
  uint144: { short: "u18", size: 18, integer: true },
  uint152: { short: "u19", size: 19, integer: true },
  uint160: { short: "u20", size: 20, integer: true },
  uint168: { short: "u21", size: 21, integer: true },
  uint176: { short: "u22", size: 22, integer: true },
  uint184: { short: "u23", size: 23, integer: true },
  uint192: { short: "u24", size: 24, integer: true },
  uint200: { short: "u25", size: 25, integer: true },
  uint208: { short: "u26", size: 26, integer: true },
  uint216: { short: "u27", size: 27, integer: true },
  uint224: { short: "u28", size: 28, integer: true },
  uint232: { short: "u29", size: 29, integer: true },
  uint240: { short: "u30", size: 30, integer: true },
  uint248: { short: "u31", size: 31, integer: true },
  uint256: { short: "u32", size: 32, integer: true },
  void:    { short: "v", size: 32 }
};

for(var i in types) types[i].type = i;

module.exports = types;
